apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "greetings.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "greetings.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "greetings.name" . }}
        release: {{ .Release.Name }}
        # To force the pod being recreated even if it has the same tag
        date: {{ now | unixEpoch | quote }}
    spec:
      containers:
        - name: {{ template "greetings.container-name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.service.port }}
          env:
            - name: HTTP_PORT
              value: {{ quote .Values.env.service.port }}
            - name: REDIS_HOST
              value: {{ quote .Values.env.redis.host }}
            - name: REDIS_PORT
              value: {{ quote .Values.env.redis.port }}
            - name: CPP_SERVICE_HOST
              value: {{ quote .Values.env.cppService.host }}
            - name: CPP_SERVICE_PORT
              value: {{ quote .Values.env.cppService.port }}
            - name: JPOD_SERVICE_HOST
              value: {{ quote .Values.env.jpodService.host }}
            - name: JPOD_SERVICE_PORT
              value: {{ quote .Values.env.jpodService.port }}
            - name: PYPOD_SERVICE_HOST
              value: {{ quote .Values.env.pypodService.host }}
            - name: PYPOD_SERVICE_PORT
              value: {{ quote .Values.env.pypodService.port }}
