apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http-server
spec:
  selector:
    app: {{ template "greetings.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: 30000
  type: NodePort