apiVersion: v1
kind: Service
metadata:
  name: {{ template "greetings.service-name" . }}
spec:
  selector:
    app: {{ template "greetings.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.env.service.port }}
      nodePort: 30000
  type: NodePort
