apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jpod.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jpod.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jpod.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: jpod
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.jpodHttpService.port }}
          env:
            - name: JPOD_GREETER_SERVICE_IP
              value: {{ quote .Values.env.jpodGreeterService.host }}
            - name: JPOD_GREETER_SERVICE_PORT
              value: {{ quote .Values.env.jpodGreeterService.port }}
            - name: JPOD_STATUS_SERVICE_IP
              value: {{ quote .Values.env.jpodStatusService.host }}
            - name: JPOD_STATUS_SERVICE_PORT
              value: {{ quote .Values.env.jpodStatusService.port }}
            - name: JPOD_HTTP_IP
              value: {{ quote .Values.env.jpodHttpService.host }}
            - name: JPOD_HTTP_PORT
              value: {{ quote .Values.env.jpodHttpService.port }}
            - name: CPPOD_SERVICE_IP
              value: {{ quote .Values.env.cppService.host }}
            - name: CPPOD_SERVICE_PORT
              value: {{ quote .Values.env.cppService.port }}
            - name: PYPOD_SERVICE_IP
              value: {{ quote .Values.env.pyService.host }}
            - name: PYPOD_SERVICE_PORT
              value: {{ quote .Values.env.pyService.port }}
