apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jpod.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jpod.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: java-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JPOD_HTTP_PORT
              value: {{ quote .Values.service.port }}
