apiVersion: v1
kind: Service
metadata:
  name: {{ template "jpod.grpc-service-name" . }}
spec:
  selector:
    app: {{ template "jpod.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.jpod.port }}
      targetPort: {{ .Values.env.jpod.port }}
