apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-server
spec:
  selector:
    app: {{ template "jpod.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: 30001
  type: NodePort