apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: {{ template "redis.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379