apiVersion: v1
kind: Service
metadata:
  name: {{ template "py.service-name" . }}
spec:
  selector:
    app: {{ template "py.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.env.service.port }}
      nodePort: 30002
  type: NodePort
