apiVersion: v1
kind: Service
metadata:
  name: {{ template "status.service-name" . }}
spec:
  selector:
    app: {{ template "py.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.statusService.port }}
      targetPort: {{ .Values.env.statusService.port }}
