apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cpp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cpp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cpp.name" . }}
        release: {{ .Release.Name }}
        # To force the pod being recreated even if it has the same tag
        date: {{ now | unixEpoch | quote }}
    spec:
      containers:
        - name: {{ template "cpp.container-name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.greeterService.port }}
            - containerPort: {{ .Values.env.statusService.port }}
          env:
            - name: GREETER_SERVICE_PORT
              value: {{ quote .Values.env.greeterService.port }}
            - name: GREETER_SERVICE_ADDRESS
              value: {{ quote .Values.env.greeterService.address }}
            - name: STATUS_SERVICE_PORT
              value: {{ quote .Values.env.statusService.port }}
            - name: STATUS_SERVICE_ADDRESS
              value: {{ quote .Values.env.statusService.address }}
