apiVersion: v1
kind: Service
metadata:
  name: {{ template "cpp.service-name" . }}
spec:
  selector:
    app: {{ template "cpp.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.service.port }}
      targetPort: {{ .Values.env.service.port }}
